config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get 'index/view'
  get 'search/person'
  post 'search/person'

  root 'index#view'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/index.rb
class Index < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
	@@num =[]
	@@name =[]
	def self.num=(num)
		@@num.push(num)
	end
	def self.num()
		@@num
	end
	def self.name=(name)
		@@name += name
	end
	def self.name()
		@@name
	end

	def self.reset_static_variables()
		@@num = []
		@@name = []
		
	end
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  layout'application'
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  layout'application'
  def view
  	Person.reset_static_variables
  	 

  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def person
		@keywords = params[:search][:keyword]
		@keywords = @keywords.split(",")
		Person.num = @keywords[0]
		@keywords.shift
		Person.name = @keywords
		phoneQuery=""
		Person.num.each do |n|
			phoneQuery += " phone like '%#{n}%' or"
		end
		phoneQuery = phoneQuery[0,phoneQuery.length - 2]
		nameQuery = " and "
		Person.name.each do |nm|
			nameQuery +=" name like '%#{nm}%' or"
		end
		nameQuery = nameQuery[0,nameQuery.length - 2]
		query = phoneQuery + nameQuery
		puts query
		 @contacts = Contact.where(query)
		 puts @contacts
		respond_to do |format|
			format.html { redirect_to :controller=>"search",:action=>"index"}
			format.js
		end		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div id="wrapper">
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>
</div>

app/views/contacts/index.html.erb
<div id="wrapper">
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.phone %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>
<%= link_to 'Back', root_path %>
</div>

app/views/contacts/new.html.erb
<div id="wrapper">
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>
</div>

app/views/contacts/show.html.erb
<div id="wrapper">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>
</div>

app/views/index/view.html.erb
<style> 
.display{
    height:70px;
    width:100%;

}
.num{
    height:100%;
    width:100%;
    text-align: center;
    font-size: 34px;
}
.list{
    height: 0%;
    width: 100%;
    overflow: scroll;
}
.phone {
    padding-top: 5px!important;
  -webkit-transition: -webkit-transform .6s ease-in-out;
  transition: transform .6s ease-in-out;
}
.phone:hover {
    background-color:#FE372D;
  -webkit-transform: rotate(360deg);
  transform: rotate(140deg);

}
.special{
    padding-top: 3px!important;
}
</style> 

<div id="wrapper">    
    <div class="display">
        <div id="destination"class="num"></div>
        <div class="list"id="txtarea"></div>
    </div>
    <%= form_for :search, :url=>{:controller=>"search",:action=>"person"}, :remote=>true do |f|%>
    <%= f.hidden_field("keyword",:value=>"1") %>
    <button type="submit" class="key" rel="1">1</button type="submit">
    <% end %>
    <%= form_for :search, :url=>{:controller=>"search",:action=>"person"}, :remote=>true do |f|%>
    <%= f.hidden_field("keyword",:value=>"2,a,b,c") %>
    <button type="submit" class="key" rel="2">2<span>abc</span></button>
    <% end %>
    <%= form_for :search, :url=>{:controller=>"search",:action=>"person"}, :remote=>true do |f|%>    
    <%= f.hidden_field("keyword",:value=>"3,d,e,f") %>
    <button type="submit" class="key" rel="3">3<span>def</span></button>
    <% end %>
    
    <div class="clear"></div>
    
    <%= form_for :search, :url=>{:controller=>"search",:action=>"person"}, :remote=>true do |f|%>    
    <%= f.hidden_field("keyword",:value=>"4,g,h,i") %>
    <button type="submit" class="key" rel="4">4<span>ghi</span></button>
    <% end %>
    <%= form_for :search, :url=>{:controller=>"search",:action=>"person"}, :remote=>true do |f|%>    
    <%= f.hidden_field("keyword",:value=>"5,j,k,i") %>
    <button type="submit" class="key" rel="5">5<span>jkl</span></button>
    <% end %>
    <%= form_for :search, :url=>{:controller=>"search",:action=>"person"}, :remote=>true do |f|%>    
    <%= f.hidden_field("keyword",:value=>"6,m,n,o") %>
    <button type="submit" class="key" rel="6">6<span>mno</span></button>
    <% end %>
    
    <div class="clear"></div>
    
    <%= form_for :search, :url=>{:controller=>"search",:action=>"person"}, :remote=>true do |f|%>    
    <%= f.hidden_field("keyword",:value=>"7,p,q,r,s") %>
    <button type="submit" class="key" rel="7">7<span>pqrs</span></button>
    <% end %>
    <%= form_for :search, :url=>{:controller=>"search",:action=>"person"}, :remote=>true do |f|%>    
    <%= f.hidden_field("keyword",:value=>"8,t,u,v") %>
    <button type="submit" class="key" rel="8">8<span>tuv</span></button>
    <% end %>
    <%= form_for :search, :url=>{:controller=>"search",:action=>"person"}, :remote=>true do |f|%>    
    <%= f.hidden_field("keyword",:value=>"9,w,x,y,z") %>
    <button type="submit" class="key" rel="9">9<span>wxyz</span></button>
    <% end %>
    
    <div class="clear"></div>

    <%= form_for :search, :url=>{:controller=>"search",:action=>"person"}, :remote=>true do |f|%>    
    <%= f.hidden_field("keyword",:value=>"*") %>
    <button type="submit" class="key special" rel="*">*</button>
    <% end %>
    <%= form_for :search, :url=>{:controller=>"search",:action=>"person"}, :remote=>true do |f|%>    
    <%= f.hidden_field("keyword",:value=>"0,+") %>
    <button type="submit" class="key" rel="0">0<span>+</span></button>
    <% end %>
    <%= form_for :search, :url=>{:controller=>"search",:action=>"person"}, :remote=>true do |f|%>    
    <%= f.hidden_field("keyword",:value=>"#") %>
    <button type="submit" class="key special" rel="#">#</button>
    <% end %>
   
    <div class="clear"></div>
    <%= link_to( "contacts", :action => "index")do %>
        <div class="key nb" rel="">Add</div>
    <% end  %>
    
    <div class="key phone" rel=""><i class="fa fa-phone"></i></div>
    <div class="key nb clr" rel=""><i class="fa fa-reply"></i></div>
    <div class="clear"></div>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phonepad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <link href='http://fonts.googleapis.com/css?family=Lato:100,300' rel='stylesheet' type='text/css'>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

  <%= csrf_meta_tags %>

</head>
<body>
<%= yield %>

</body>
</html>

app/views/search/person.js.erb
$(document).ready(function(){
	if ($('#txtarea').html("")) {
   $('.display').css({'height' : '300px'});
   $('.num').css({'height' : '20%'});
   $('.list').css({'height' : '80%'});
} else {
   alert('The container is empty.');
}
});

$("#txtarea").fadeOut(500,function(){
	$(this).html("");
	<% @contacts.each do |c| %>
		$("#txtarea").append('<h3><%= c.name %></h3><h4><br><%= c.phone %></h4>').fadeIn(500);
	<% end %>
});